site_name: "Prestige Docs"
site_description: "Documentation for the Prestige HTTP client."
site_url: "https://prestige.dev/docs/"
site_author: "Shrikant Sharat Kandula"

repo_url: "https://github.com/sharat87/prestige"
edit_uri: "edit/master/docs/content/"

docs_dir: "content"

theme:
  name: null
  custom_dir: "theme"

markdown_extensions:
  - "markdown_ext"  # Local extension for custom behaviour and features.
  - "toc":
      marker: ""
      permalink: true
      toc_depth: "1-5"
  - "attr_list"
  - "admonition"
  - "smarty"
  - "def_list"
  # TODO: We need to use CodeMirror's runmode with Prestige's mode to highlight code snippets in docs.
  # - "codehilite":
  #     linenums: true
  #     guess_lang: false

nav:
  - "index.md"
  - "Guides":
    - "guides/syntax.md"
    - "guides/response-pane.md"
    - "guides/javascript-blocks.md"
    - "guides/templating.md"
    - "guides/cookie-management.md"
    - "guides/file-bucket.md"
    - "guides/sheet-browser.md"
    - "guides/proxy.md"
    - "guides/editor.md"
    - "guides/event-handling.md"
  - "api-reference.md"
  - "tips.md"
  - "about.md"
